#!/usr/bin/env python3
import pygame
from pygame.locals import *
import liblait.pyganim
from liblait import scalehandler, Settings, mainmenu, settingsmenu
import yaml
import os, sys


if __name__ == '__main__':
    GAMEDIR=os.path.dirname(os.path.realpath(__file__))
    settings = Settings.SETTINGS(GAMEDIR)
    pygame.display.init()
    pygame.display.set_caption("Lilly's Adventures in Toyland")
    pygame.mixer.init()
    pygame.font.init()
    flags = 0
    if settings.fullscreen:
        flags = pygame.FULLSCREEN|pygame.HWSURFACE
    elif settings.borderless:
        flags = pygame.NOFRAME|pygame.RESIZABLE
    else:
        flags = pygame.RESIZABLE
    screen = pygame.display.set_mode((settings.res_x,settings.res_y),flags)
    nextaction = ''
    while nextaction != 'quit':
        nextaction = mainmenu.mainMenu(screen,settings,flags).run()
        if nextaction == 'settings':
            nextaction = settingsmenu.settingsMenu(screen,settings, flags).run()
    pygame.quit()
    sys.exit()
