Borderless: False
Fullscreen: false
Joystick: 360.yml
JoystickNumber: 0
Language: English
Languages:
- English
Loglevel: DEBUG
Loglevels:
- DEBUG
- INFO
- WARNING
- ERROR
- CRTICAL
Resolution:
  h: 768
  w: 1024
Volume:
  fx: 20.0
  music: 20.0
  voice: 12.0
