Borderless: false
Fullscreen: false
Joystick: 360.yml
JoystickNumber: 0
Language: English
Languages:
- English
Logfile: lait.log
Loglevel: DEBUG
Resolution:
  h: 768
  w: 1024
Volume:
  fx: 38.0
  music: 38.0
  voice: 100.0
