Borderless: true
Fullscreen: false
Joystick: 360.yml
JoystickNumber: 0
Language: English
Languages:
- English
Logfile: lait.log
Loglevel: DEBUG
Resolution:
  h: 1080
  w: 1920
Volume:
  fx: 38.0
  music: 38.0
  voice: 100.0
