Borderless: false
Fullscreen: false
Language: English
Joystick: 360.yml
JoystickNumber: 0
Languages:
- English
Loglevel: DEBUG
Loglevels:
- DEBUG
- INFO
- WARNING
- ERROR
- CRTICAL
Resolution:
  h: 800
  w: 1280
Volume:
  fx: 20.0
  music: 20.0
  voice: 12.0
